name: trader-bot
channels:
  - defaults
dependencies:
  - pip=21.0.1
  - python=3.8.5
  - pip:
    - pytest==5.3.2
    - panda==0.3.1
    - pandas_datareader==0.9.0
    - matplotlib==3.3.4 
    - scipy==1.6.2
    - cython==0.29.22
    - TA-lib==0.4.19
